InterSpice/InterSpice/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import handler404, static, url
from django.conf import settings
from . import views

app_name = 'InterSpice'

urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('album/', include('album.urls')),
    path('book/', include('book.urls')),
    path('article/', include('article.urls')),
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = views.page_not_found

InterSpice/article/urls.py
from django.urls import path

from . import views

app_name = 'article'

urlpatterns = [
    path('post/list/<int:page>/<int:category_id>', views.PostListView.as_view(), name='list_post'),
    path('post/detail/<int:post_id>', views.PostDetailView.as_view(), name='detail_post'),
    path('post/addcomment/<int:post_id>', views.PostAddCommentView.as_view(), name='add_comment'),
]

InterSpice/book/urls.py
from django.urls import path

from . import views

app_name = 'book'

urlpatterns = [
    path('book_info/list/<int:page>/<int:category_id>/', views.BookListView.as_view(), name='list_book'),
]

InterSpice/article/models.py
import os.path
from ckeditor_uploader import fields
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.shortcuts import reverse
from django.conf import settings
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(unique=True, max_length=30, blank=True, null=True)

    class Meta:
        managed = False

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("list_post", )
    
    def get_private_posts(self):
        return self.posts.filter(is_private=0)


class Post(models.Model):
    title = models.CharField(max_length=60, blank=True, null=True)
    body = RichTextUploadingField(
        blank=True,
        null=True,
        config_name="my-custom-toolbar"
    )
    timestamp = models.DateTimeField(blank=True, null=True,  default=timezone.now)
    can_comment = models.IntegerField(blank=True, null=True)
    category = models.ForeignKey(Category, models.DO_NOTHING, blank=True, null=True, related_name="posts")
    is_private = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False

    def __str__(self) -> str:
        return f"{str(self.category)}_{self.title}"


class Comment(models.Model):
    author = models.CharField(max_length=30, blank=True, null=True)
    email = models.CharField(max_length=254, blank=True, null=True)
    site = models.CharField(max_length=255, blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    from_admin = models.IntegerField(blank=True, null=True)
    reviewed = models.IntegerField(blank=True, null=True)
    timestamp = models.DateTimeField(blank=True, null=True, default=timezone.now)
    replied = models.ForeignKey('self', models.DO_NOTHING, blank=True, null=True)
    post = models.ForeignKey('Post', models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False

    def __str__(self) -> str:
        return self.body


class Link(models.Model):

    name = models.CharField(max_length=30, blank=True, null=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    type = models.IntegerField(null=True, default=1)

    class Meta:
        managed = False


class About(models.Model):

    cover = models.ImageField(upload_to='album', null=True)
    introduction = models.CharField(max_length=1000, blank=True, null=True)

InterSpice/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block left_content %}
			<!-- List-Group Panel -->
			<div class="panel panel-default">
				<div class="panel-heading">
					<h1 class="panel-title"><span class="glyphicon glyphicon-random"></span> Links</h1>
				</div>
				<div class="list-group">
				    {% for link in links%}
					<a href="{{link.url}}" class="list-group-item">{{link.name}}</a>
					{% endfor%}
				</div>
			</div>
				
{% endblock left_content %}
  
{% block center_content %}	
			<!-- Articles -->
			<div class="row">
				<article class="col-xs-12">
                    <div class="entry-content">
					<p><span style="line-height: 1.5;"><b><img loading="lazy" class="alignleft wp-image-1952 size-medium" src="{% static 'background/20211109160937.jpg' %}" alt="" style="max-width:600px;" ></a></b></span></p>
                    {% autoescape off %}
						{{profile.content}}
					{% endautoescape %}
<!-- .entry-content --></div> <!-- entry-content --><div class="heatmapthemead-featured-page-clear">&nbsp;</div>
				</article>
			</div>
{% endblock center_content %}

InterSpice/templates/base.html
{% load static %}
<!DOCTYPE html>
<!-- Template by Quackit.com -->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>InterSpice</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom CSS: You can use this stylesheet to override any Bootstrap styles and/or apply your own styles -->
    <link href="{% static 'css/custom.css'%}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'js/jquery-1.11.3.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-paginator.js'%}"></script>

    <link href="{% static 'plugins/fullcalendar/main.css'%}" rel="stylesheet">
    <script type="text/javascript" src="{% static 'plugins/fullcalendar/main.js'%}"></script>

    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            initialView: 'dayGridMonth',
            locale: "zh",
            eventTextColor:"red",
        });
        calendar.render();
        });
    </script>
    <style>
    .bg1 {
          background-image: url({% static background_image %});
          -moz-background-size:100% 100%; 
          background-size:100% 100%;
          min-height:400px;
     }
     .fc-col-header-cell-cushion {
         color:black;
     }
     .fc-daygrid-day-number{
         color:black;
     }
     .bottom{
         color: #9d9d9d;
         margin: 15px auto;
     }
     .bottom->p{
        
     }
     .v-align-middle{
          vertical-align: middle;
     }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
        <div class="container">
            <!-- Logo and responsive toggle -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="glyphicon glyphicon-user"></a>
                    </li>
                    <li>
                        <a href="{% url 'index' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'about' %}">About Me</a>
                    </li>
                    <li>
                        <a href="{% url 'article:list_post' 1 0 %}">Posts</a>
                    </li>
                    <li>
                        <a href="{% url 'book:list_book' 1 0 %}">Books</a>
                    </li>
					<li>
                        <a href="#">Photos</a>
                    </li>
					{% comment %} <li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Services <span class="caret"></span></a>
						<ul class="dropdown-menu" aria-labelledby="about-us">
							<li><a href="#">Engage</a></li>
							<li><a href="#">Pontificate</a></li>
							<li><a href="#">Synergize</a></li>
						</ul>
					</li>  {% endcomment %}
                    {% if request.user.is_authenticated %}} 
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li
                    {% endif %}  
                </ul>

				<!-- Search -->
				<form class="navbar-form navbar-right" role="search" method="get" action="{% url 'article:list_post' 1 0 %}">
					<div class="form-group">
						<input type="text" class="form-control" name="keyword" value="{{keyword}}">
					</div>
					<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Search</button>
				</form>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<div class="container-fluid bg1">
    <!-- Left Column -->
    <div class="col-sm-3">
    {% block left_content %}{% endblock left_content %}
    </div>
    <!-- Center Column -->
    <div class="col-sm-6">
     {% block center_content %}{% endblock center_content %}
    </div>
    <!-- Right Column -->
    <div class="col-sm-3">
        {% if not request.user.is_authenticated%}
        <!-- Form --> 
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-log-in"></span> 
                        Login
                    </h3>
                </div>
                <div class="panel-body">
                    <form action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control" id="uid" name="username" placeholder="Username">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" id="pwd" name="password" placeholder="Password">
                        </div>
                        <button type="submit" class="btn btn-default">Login</button>
                    </form>
                </div>
            </div>
        {% endif %}
       <div id='calendar'></div>
       <div style="margin-top:20px;margin-left:2px;">
        <svg height="32" aria-hidden="true" viewBox="0 0 16 16" version="1.1" width="32" data-view-component="true" class="octicon octicon-mark-github v-align-middle">
            <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"></path>
        </svg>
        <a href="https://github.com/mcfee-618" class="v-align-middle" style="color:#555; margin-left:10px;"> Github Link </a>
       </div>
    </div>
</div>

<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">

    
        <div class="container">

            <div class="collapse navbar-collapse" id="navbar">
                <div class="bottom">
                        <div style="text-align:center;"><a href="https://beian.miit.gov.cn/">京ICP备2021036847号-1</a></div>
                        <div style="text-align:center;"><span>热爱生活 享受生活<span> | <span>勇敢坚强<span> | <span>责任担当<span></div>
                        <div style="text-align:center;">Copyright &copy; www.interspice.net 2021 </div>
                </div>
            </div>
        </div>
        <!-- /.container -->
    </nav>

</body>

</html>

InterSpice/templates/index.html
{% extends 'base.html' %}

{% block left_content %}
			<!-- List-Group Panel -->
			<div class="panel panel-default">
				<div class="panel-heading">
					<h1 class="panel-title"><span class="glyphicon glyphicon-random"></span> 技术链接</h1>
				</div>
				<div class="list-group">
				    {% for link in links%}
					<a href="{{link.url}}" class="list-group-item">{{link.name}}</a>
					{% endfor%}
				</div>
			</div>	
				
{% endblock left_content %}
  
{% block center_content %}
			<!-- Alert -->
			{% if alert_msg %}
			<div class="alert alert-success alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<strong></strong> {{alert_msg}}
			</div>
			{% endif %}		
	        {% for post in posts %}	
			<!-- Articles -->
			<div class="row">
				<article class="col-xs-12">
					<h2>{{post.title}}</h2>
					<p>			
						{% autoescape off %}
			  			{{ post.body |striptags | truncatechars:100  }}
						{% endautoescape %}
					</p>
					<p><a class="btn btn-default" href="{% url 'article:detail_post' post.id %}">Read More</a></p>
					<p class="pull-right"><span class="label label-default"></span></p>
					<ul class="list-inline">
						<li><a href="#">{{post.timestamp|date:"Y-m-d"}}</a></li>
						<li><a href="#"><span class="glyphicon glyphicon-comment"></span> {{post.comment_set.all|length}} Comments</a></li>
						<li><a href="#"><span class="glyphicon glyphicon-share"></span> 8 Shares</a></li>
					</ul>
				</article>
			</div>
			<hr>
			{% endfor%}
{% endblock center_content %}