InterSpice/InterSpice/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import handler404, static, url
from django.conf import settings
from . import views

app_name = 'InterSpice'

urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('album/', include('album.urls')),
    path('book/', include('book.urls')),
    path('article/', include('article.urls')),
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = views.page_not_found

InterSpice/article/urls.py
from django.urls import path

from . import views

app_name = 'article'

urlpatterns = [
    path('post/list/<int:page>/<int:category_id>', views.PostListView.as_view(), name='list_post'),
    path('post/detail/<int:post_id>', views.PostDetailView.as_view(), name='detail_post'),
    path('post/addcomment/<int:post_id>', views.PostAddCommentView.as_view(), name='add_comment'),
]

InterSpice/book/urls.py
from django.urls import path

from . import views

app_name = 'book'

urlpatterns = [
    path('book_info/list/<int:page>/<int:category_id>/', views.BookListView.as_view(), name='list_book'),
]

InterSpice/article/models.py
import os.path
from ckeditor_uploader import fields
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.shortcuts import reverse
from django.conf import settings
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(unique=True, max_length=30, blank=True, null=True)

    class Meta:
        managed = False

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("list_post", )
    
    def get_private_posts(self):
        return self.posts.filter(is_private=0)


class Post(models.Model):
    title = models.CharField(max_length=60, blank=True, null=True)
    body = RichTextUploadingField(
        blank=True,
        null=True,
        config_name="my-custom-toolbar"
    )
    timestamp = models.DateTimeField(blank=True, null=True,  default=timezone.now)
    can_comment = models.IntegerField(blank=True, null=True)
    category = models.ForeignKey(Category, models.DO_NOTHING, blank=True, null=True, related_name="posts")
    is_private = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False

    def __str__(self) -> str:
        return f"{str(self.category)}_{self.title}"


class Comment(models.Model):
    author = models.CharField(max_length=30, blank=True, null=True)
    email = models.CharField(max_length=254, blank=True, null=True)
    site = models.CharField(max_length=255, blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    from_admin = models.IntegerField(blank=True, null=True)
    reviewed = models.IntegerField(blank=True, null=True)
    timestamp = models.DateTimeField(blank=True, null=True, default=timezone.now)
    replied = models.ForeignKey('self', models.DO_NOTHING, blank=True, null=True)
    post = models.ForeignKey('Post', models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False

    def __str__(self) -> str:
        return self.body


class Link(models.Model):

    name = models.CharField(max_length=30, blank=True, null=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    type = models.IntegerField(null=True, default=1)

    class Meta:
        managed = False


class About(models.Model):

    cover = models.ImageField(upload_to='album', null=True)
    introduction = models.CharField(max_length=1000, blank=True, null=True)

InterSpice/article/forms.py
from django import forms
from .models import Comment
class CommentPostForm(forms.ModelForm):
   class Meta:
       # 指明数据模型来源
       model = Comment
       # 定义表单包含的字段
       fields = ('author', 'email', "body" )

InterSpice/article/views.py
import markdown
from django.core.paginator import Paginator
from django.db.models import Q
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_http_methods
from InterSpice.views import BaseView
from .models import Post, Category
from .forms import CommentPostForm
from InterSpice.tags import get_range


class PostListView(BaseView):
    def get(self, request, page=1, category_id=0, *args, **kwargs):
        keyword = request.GET.get("keyword")
        posts = Post.objects
        categories = Category.objects.all()
        if not request.user.is_authenticated:
            posts = posts.filter(is_private=0)
        if category_id:
            posts = posts.filter(category_id=category_id)
        else:
            posts = posts.all()
        if keyword:
            posts = posts.filter(Q(body__contains=keyword) | Q(title__contains=keyword))
        posts = posts.order_by('-timestamp')
        paginator = Paginator(posts, 5)
        pageinfo = paginator.page(page)
        context = {"pageinfo": pageinfo, "categories": categories, "category_id": category_id}
        if keyword:
            context.update({"keyword": keyword})
        return self.render(request, "article/list_post.html", context=context)


class PostDetailView(BaseView):
    def get(self, request, post_id, *args, **kwargs):
        post = get_object_or_404(Post, pk=post_id)
        post.body = markdown.markdown(post.body,
                                extensions=[
                                    'markdown.extensions.extra',
                                    'markdown.extensions.codehilite',
                                    'markdown.extensions.toc',
                                ])
        
        categories = Category.objects.all()
        comments = post.comment_set.all()
        context = {"post": post, "categories": categories, "comments": comments}
        return self.render(request, "article/detail_post.html", context=context)


class PostAddCommentView(BaseView):
    def post(self, request, post_id, *args, **kwargs):
        post = get_object_or_404(Post, pk=post_id)
        comment_post_form = CommentPostForm(request.POST)
        if comment_post_form.is_valid():
            new_comment = comment_post_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect(reverse("article:detail_post", args=[post.id]))
        return redirect(reverse("article:detail_post", args=[1]))

InterSpice/templates/article/detail_post.html
{% extends 'base.html' %}
{% load static %}

{% block left_content %}
			<!-- List-Group Panel -->
	<div class="panel panel-default">
		<div class="panel-heading">
			<h1 class="panel-title"> Categories</h1>
		</div>
		<ul class="list-group">
		{% for category in categories %}
		 <li class="list-group-item">
		  <span><a href="{% url 'article:list_post' 1 category.id   %}" class="inline-block">{{ category.name }}</a></span>
		  <span class="badge badge-primary badge-pill"> {{ category.posts.all|length}}</span>
		 </li>
		{% endfor%}
		</ul>
	</div>
{% endblock left_content %}

{% block center_content %}
  
	<!-- Articles -->
	<div class="row">
		<article class="col-xs-12">
			<header class="entry-header">
				<h2 class="entry-title">{{ post.title}}</h2>
				<div class="entry-meta">
					<span class="byline"><i class="fa fa-user"></i><span class="author vcard"><a class="url fn n" style="color:black;" href="http://xiaorui.cc/archives/author/rfyiamcool">{{ post.category.name }}</a></span></span> &nbsp; | &nbsp; <span class="posted-on"><i class="fa fa-calendar"></i>
					<a href="#" rel="bookmark" style="color:black;">
					<time class="entry-date published" datetime="{{post.timestamp}}">{{ post.timestamp | date:"Y年m月d日"}}</time></a></span>
					&nbsp; | &nbsp;
					<span class="comments-link">
				    	<a href="#" style="color:black;">{{ comments | length}} Comments</a>			
					</span>
				</div>
	        </header>
			<div class="body">
				{% autoescape off %}
			  		{{ post.body }}
				{% endautoescape %}
			</div>
		</article>
	</div>
	<h3>Add Comment</h3>
	<div class="col-md-offset-0">
	</div>

	 <hr>

	<form action="{% url "article:add_comment" post.id %}" method="post" class="form" >
	    {% csrf_token %}
    	<div class="form-group required"><label class="form-control-label" for="author">Name</label>                             
        	<input class="form-control" id="author" name="author" required type="text" value="">             
    	</div>
    	<div class="form-group required"><label class="form-control-label" for="email">Email</label>
            <input class="form-control" id="email" name="email" required type="text" value="">    
        </div>
    	{% comment %} <div class="form-group"><label class="form-control-label" for="site">Site</label>        
            <input class="form-control" id="site" name="site" type="text" value="">           
        </div> {% endcomment %}
    	<div class="form-group required"><label class="form-control-label" for="body">Comment</label>             
        	<textarea class="form-control" id="body" name="body" required></textarea>
        </div>
            <input class="btn btn-secondary" id="submit" name="submit" type="submit" value="Submit">  
    </form>

	 <div class="comments" id="comments">
                <h3>{{post.comment_set.all|length}} Comments</h3>
                    <ul class="list-group">
                        {% for comment in post.comment_set.all%}
                            <li class="list-group-item list-group-item-action flex-column">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">
                                        <a href="/"
                                           target="_blank">
                                                {{comment.author}}                                          
                                        </a>
                                        
                                            <span class="badge badge-primary">Author</span>                                
                                    </h5>
                                    <small data-toggle="tooltip" data-placement="top" data-delay="500"
                                           data-timestamp="2020-04-17T16:14:29Z">
                                        <span class="flask-moment" data-timestamp="2020-04-17T16:14:29Z" data-format="fromNow(0)" data-refresh="0" style="display: none">2020-04-17T16:14:29Z</span>
                                    </small>
                                </div>
                                <p class="mb-1">{{comment.body}}</p>
                            </li>
					    {% endfor %}
					</ul>
				</div>
{% endblock center_content %}

InterSpice/templates/article/list_post.html
{% extends 'base.html' %}
{% load static %}
{% block left_content %}
			<!-- List-Group Panel -->
	<div class="panel panel-default">
		<div class="panel-heading">
			<h1 class="panel-title"> Categories</h1>
		</div>
		<ul class="list-group">
		{% for category in categories %}
		 <li class="list-group-item">
		  <span><a href="{% url 'article:list_post' 1 category.id   %}?keyword={{keyword}}" class="inline-block">{{ category.name }}</a></span>
		  <span class="badge badge-primary badge-pill"> 
		  {% if request.user.is_authenticated %}
		  {{ category.posts.all|length}}
		  {% else%}
		  {{ category.get_private_posts|length}}
		  {% endif%}
		  </span>
		 </li>
		{% endfor%}
		</ul>
	</div>
{% endblock left_content %}

{% block center_content %}
  
	{% for post in pageinfo.object_list%}	
	<!-- Articles -->
	<div class="row">
		<article class="col-xs-12">
			<h2>{{ post.title }}</h2>
			<p>
			{% autoescape off %}
			  	{{ post.body |striptags | truncatechars:100  }}
			{% endautoescape %}
			</p>
			<p><a class="btn btn-default" href="{% url 'article:detail_post' post.id %}">more</button></a>
			<p class="pull-right"><span class="label label-default">keyword</span> <span class="label label-default">tag</span> <span class="label label-default">post</span></p>
			<ul class="list-inline">
				<li><a href="#">{{ post.timestamp | date:"Y年m月d日"}}</a></li>
				<li><a href="#"><span class="glyphicon glyphicon-comment"></span> {{ post.comment_set.all|length }} Comments</a></li>
		</article>
	</div>
	{% endfor %}
	<div class="col-md-offset-0">
      
		<div id="page" class="pagination">
		{% for _ in pageinfo.paginator.num_pages|get_range %}

			{% with start=pageinfo.number|add:-5 %}
			{% with end=pageinfo.number|add:5 %}
			{% if forloop.counter == pageinfo.number %}
				<li class="active"><a href="javascript:void(0)" title="Current page is 1">{{forloop.counter}}</a></li>	
			{% elif forloop.counter > end or forloop.counter < start %}
			{% elif forloop.last == pageinfo.paginator.num_pages %}
			   	<li><a href="{% url 'article:list_post' forloop.counter category_id %}?keyword={{keyword}}" title="Go to last page">末页</a></li>
			{% else %}
			   	<li><a href="{% url 'article:list_post' forloop.counter category_id %}?keyword={{keyword}}" title="Go to page 2">{{ forloop.counter }}</a></li>
			{% endif%}

			{% endwith %}
			{% endwith %}
		{% endfor %}
		</div>
	</div>
{% endblock center_content %}